<script>
import { select_value } from "svelte/internal";
import { onMount } from 'svelte';


  var url = "http://localhost:3000";
  var bio;
  
  
  var requestOptions = {
    method: 'GET',
    redirect: 'follow'
  };
  
  onMount(async () => {

   fetch(url, requestOptions)
    .then(response => response.text())
    .then(result => bio = result)
    .then(result => console.log(result))
    .catch(error => console.log('error', error));

  });

	
	
	

</script>

<main>
	
	{#if bio === undefined}
	<h2>loading...</h2>
	{:else}
	<h2 class="tilt-in-top-1">"{bio}"</h2>
	{/if}

</main>

<style>

.tilt-in-top-1 {
	-webkit-animation: tilt-in-top-1 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
	        animation: tilt-in-top-1 0.6s cubic-bezier(0.250, 0.460, 0.450, 0.940) both;
}

	main {
		text-align: center;
		padding: 1em;
		max-width: 240px;
		margin: 0 auto;
	}

	@import url('https://fonts.googleapis.com/css2?family=Cutive+Mono&display=swap');

	h2 {
		color: black;
		font-family: 'Cutive Mono', monospace;
		font-size: 4em;
		font-weight: 100;
	}

	@media (min-width: 640px) {
		main {
			max-width: none;
		}
	}

	/* ----------------------------------------------
 * Generated by Animista on 2021-5-28 13:4:52
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation tilt-in-top-1
 * ----------------------------------------
 */
@-webkit-keyframes tilt-in-top-1 {
  0% {
    -webkit-transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
            transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0deg) translateY(0) skewY(0deg);
            transform: rotateY(0deg) translateY(0) skewY(0deg);
    opacity: 1;
  }
}
@keyframes tilt-in-top-1 {
  0% {
    -webkit-transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
            transform: rotateY(30deg) translateY(-300px) skewY(-30deg);
    opacity: 0;
  }
  100% {
    -webkit-transform: rotateY(0deg) translateY(0) skewY(0deg);
            transform: rotateY(0deg) translateY(0) skewY(0deg);
    opacity: 1;
  }
}

</style>